export const base = {
    FONT_SIZE_TINY: 8,
    FONT_SIZE_SEMISMALL: 10,
    FONT_SIZE_SMALL: 12,
    FONT_SIZE_SEMIMEDIUM: 13,
    FONT_SIZE_MEDIUM: 14,
    FONT_SIZE_SEMILARGE: 16,
    FONT_SIZE_LARGE: 18,
    FONT_SIZE_EXTRA_LARGE: 24,
    FONT_SIZE_SEMIMASSIVE: 28,
    FONT_SIZE_MASSIVE: 34,
  
    FONT_WEIGHT_LIGHT: '200',
    FONT_WEIGHT_SEMIMEDIUM: '400',
    FONT_WEIGHT_MEDIUM: '500',
    FONT_WEIGHT_BOLD: '700',
  
    PRIMARY_FONT_FAMILY: 'AvertaDemo-Regular',
    PRIMARY_FONT_FAMILY_BOLD: 'AvertaDemo-ExtraBoldItalic',
  
    SECONDARY_FONT_FAMILY: 'Product-Sans-Regular',
    SECONDARY_FONT_FAMILY_ITALIC: 'Product-Sans-Italic',
    
    SHADOW: 'rgba(153, 153, 153, 0.3)',
    TRANSPARENT: 'rgba(0, 0, 0, 0)',
    WHITE: 'rgba(255, 255, 255, 1)',
    WHITE10: 'rgba(255, 255, 255, 0.10)',
    WHITE25: 'rgba(255, 255, 255, 0.25)',
    WHITE50: 'rgba(255, 255, 255, 0.50)',
    WHITE75: 'rgba(255, 255, 255, 0.75)',
    WHITE85: 'rgba(255, 255, 255, 0.85)',
    WHITE90: 'rgba(255, 255, 255, 0.90)',
    BLACK20: 'rgba(0, 0, 0, 0.2)',
    BLACK30: 'rgba(0, 0, 0, 0.3)',
    BLACK50: 'rgba(0, 0, 0, 0.5)',
    BLACK: 'rgba(0, 0, 0, 1)',
    GRAYSEMILIGHT: 'rgba(217, 217, 217, 1)',
    GRAYLIGHT: 'rgba(242, 243, 245, 1)', //GRAYFBINPUT
    GRAYFBINPUTTEXT: 'rgba(141, 148, 158, 1)',
    YELLOW: 'rgba(246, 173, 0, 1)',
    RED: 'rgba(255, 59, 48, 1)',
    GREEN: '#4CD964',

    noImage : 'http://www.brandenforcement.co.uk/wp-content/themes/brand-enforce/img/default-placeholder.png'
  };
  
  export const darkTheme = {
    PRIMARY_BACKGROUND_COLOR: '#3d3d3d',
    PRIMARY_BACKGROUND_COLOR_LIGHT: '#797979',
  
    SECONDARY_BACKGROUND_COLOR: '#ffffff',
    SECONDARY_BACKGROUND_COLOR_LIGHT: '#f7f7f7',

    THIRD_BACKGROUND_COLOR: '#3d3d3d',
    THIRD_BACKGROUND_COLOR_LIGHT: '#333333',

    FOURTH_BACKGROUND_COLOR: '#EFEFF4',

    REDGRAY: 'rgba(237, 41, 57, 1)',

    BACKGROUND_COLOR: '#333333',

    PRIMARY_TEXT_COLOR: '#ffffff',
    PRIMARY_TEXT_COLOR_LIGHT: '#BBBBBB', //! elegir adecuado, no final
    SECONDARY_TEXT_COLOR: '#3d3d3d',
    SECONDARY_TEXT_COLOR_LIGHT: 'rgba(90, 90, 90, 1)',
    PRIMARY_TEXT_BACKGROUND_COLOR: '#3d3d3d',
    SECONDARY_TEXT_BACKGROUND_COLOR: '#ffffff'
  };
  export const lightTheme = {
    PRIMARY_BACKGROUND_COLOR: '#E6E6E6',
    PRIMARY_BACKGROUND_COLOR_LIGHT: '#f7f7f7',
  
    SECONDARY_BACKGROUND_COLOR: '#3d3d3d',
    SECONDARY_BACKGROUND_COLOR_LIGHT: '#797979',

    THIRD_BACKGROUND_COLOR: '#D1D1D1',
    THIRD_BACKGROUND_COLOR_LIGHT: '#FFFFFF',

    FOURTH_BACKGROUND_COLOR: '#EFEFF4',

    REDGRAY: 'rgba(141, 148, 158, 1)',

    BACKGROUND_COLOR: 'rgba(248, 248, 248, 0.82)',
  
    PRIMARY_TEXT_COLOR: '#000000',
    PRIMARY_TEXT_COLOR_LIGHT: '#595959',
    SECONDARY_TEXT_COLOR: '#ffffff',
    SECONDARY_TEXT_COLOR_LIGHT: 'rgba(142, 142, 147, 1)',
    THIRD_TEXT_COLOR: '#ffffff', //! checar, nunca usado
    THIRD_TEXT_COLOR_LIGHT: 'rgba(169, 169, 169, 1)',

    PRIMARY_TEXT_BACKGROUND_COLOR: '#ffffff',
    SECONDARY_TEXT_BACKGROUND_COLOR: '#3d3d3d'
  };
  
  export const colorOptions = {
    orange: {
      PRIMARY_COLOR_FAINT: '#FFF3E0',
      PRIMARY_COLOR_LIGHT: '#FFB74D',
      PRIMARY_COLOR: '#FF9800',
      PRIMARY_COLOR_BOLD: '#EF6C00',
      PRIMARY_FOREGROUND_COLOR: '#ffffff'
    },
    red: {
      PRIMARY_COLOR_FAINT: '#FFEBEE',
      PRIMARY_COLOR_LIGHT: '#E57373',
      PRIMARY_COLOR: '#F44336',
      PRIMARY_COLOR_BOLD: '#C62828',
      PRIMARY_FOREGROUND_COLOR: '#ffffff'
    },
    blue: {
      PRIMARY_COLOR_FAINT: '#E3F2FD',
      PRIMARY_COLOR_LIGHT: '#64B5F6',
      PRIMARY_COLOR: '#2196F3',
      PRIMARY_COLOR_BOLD: '#1565C0',
      PRIMARY_FOREGROUND_COLOR: '#ffffff'
    },
    cyan: {
      PRIMARY_COLOR_FAINT: '#E0F7FA',
      PRIMARY_COLOR_LIGHT: '#4DD0E1',
      PRIMARY_COLOR: '#00BCD4',
      PRIMARY_COLOR_BOLD: '#00838F',
      PRIMARY_FOREGROUND_COLOR: '#ffffff'
    },
    teal: {
      PRIMARY_COLOR_FAINT: '#E0F2F1',
      PRIMARY_COLOR_LIGHT: '#4DB6AC',
      PRIMARY_COLOR: '#009688',
      PRIMARY_COLOR_BOLD: '#00695C',
      PRIMARY_FOREGROUND_COLOR: '#ffffff'
    },
    gray: {
      PRIMARY_COLOR_FAINT: '#FAFAFA',
      PRIMARY_COLOR_LIGHT: '#E0E0E0',
      PRIMARY_COLOR: '#9E9E9E',
      PRIMARY_COLOR_BOLD: '#424242',
      PRIMARY_FOREGROUND_COLOR: '#ffffff'
    },
    purlple: {
      PRIMARY_COLOR_FAINT: '#EDE7F6',
      PRIMARY_COLOR_LIGHT: '#9575CD',
      PRIMARY_COLOR: '#673AB7',
      PRIMARY_COLOR_BOLD: '#4527A0',
      PRIMARY_FOREGROUND_COLOR: '#ffffff'
    },
    green: {
      PRIMARY_COLOR_FAINT: '#E8F5E9',
      PRIMARY_COLOR_LIGHT: '#81C784',
      PRIMARY_COLOR: '#4CAF50',
      PRIMARY_COLOR_BOLD: '#2E7D32',
      PRIMARY_FOREGROUND_COLOR: '#ffffff'
    },
    pink: {
      PRIMARY_COLOR_FAINT: '#F5E8F2',
      PRIMARY_COLOR_LIGHT: '#C781C2',
      PRIMARY_COLOR: '#FF2B4F',
      PRIMARY_COLOR_BOLD: '#7D2E5D',
      PRIMARY_FOREGROUND_COLOR: '#ffffff'
    }
  };